"""Async document-ingestion pipeline: download → parse → chunk → embed → index.

Runs inside the Celery worker (see `app/worker.py`). The heavy lifting (Docling parse,
embedding, vision LLM calls) is synchronous or async-IO; the Celery task bridges into
this async code via a single `asyncio.run(...)` per task invocation.

Chunk types produced:
  "text"   — plain text extracted from the PDF text layer
  "table"  — a Docling table exported to Markdown (no vision LLM needed, already text)
  "vision" — a description of a figure/picture generated by a vision LLM

OCR fallback: the pipeline first attempts text extraction without OCR (fast). If no text
chunks come back (image-only / scanned PDF), it retries with Docling's built-in OCR.

Chunking strategy: text items are grouped per page, capped at ~1000 chars, with the
bounding box of the first item in the group recorded as provenance. Chunks never span a
page boundary so a citation always points to exactly one page.
"""

import asyncio
import os
import tempfile
import uuid
from functools import lru_cache

from docling.document_converter import DocumentConverter
from docling_core.types.doc import BoundingBox, DoclingDocument

from app.db.session import async_session_maker
from app.models.document import Document, DocumentChunk, DocumentStatus
from app.services import storage, vector_store
from app.services.embeddings import embed_texts
from app.services.llm import describe_visual_async

CHUNK_CHAR_LIMIT = 1000


@lru_cache
def _converter() -> DocumentConverter:
    """Standard converter — no OCR. Loads layout/table models once per worker process."""
    return DocumentConverter()


@lru_cache
def _converter_ocr() -> DocumentConverter:
    """OCR-enabled converter, used as fallback for scanned/image-only PDFs."""
    from docling.datamodel.pipeline_options import PdfPipelineOptions
    from docling.document_converter import PdfFormatOption
    return DocumentConverter(
        format_options={"pdf": PdfFormatOption(pipeline_options=PdfPipelineOptions(do_ocr=True))}
    )


def _bbox_to_dict(bbox: BoundingBox | None) -> dict | None:
    if bbox is None:
        return None
    return {"l": bbox.l, "t": bbox.t, "r": bbox.r, "b": bbox.b}


def _chunk_document(doc: DoclingDocument) -> list[dict]:
    """Group text items into per-page chunks, preserving page + bbox provenance."""
    chunks: list[dict] = []
    current_page: int | None = None
    buffer_texts: list[str] = []
    buffer_bbox: dict | None = None
    buffer_len = 0

    def flush() -> None:
        nonlocal buffer_texts, buffer_bbox, buffer_len
        text = "\n".join(buffer_texts).strip()
        if text:
            chunks.append({"page_number": current_page, "text": text, "bbox": buffer_bbox, "chunk_type": "text"})
        buffer_texts, buffer_bbox, buffer_len = [], None, 0

    for item in doc.texts:
        text = (item.text or "").strip()
        if not text or not item.prov:
            continue
        prov = item.prov[0]
        page_no = prov.page_no
        if current_page is not None and (page_no != current_page or buffer_len + len(text) > CHUNK_CHAR_LIMIT):
            flush()
        current_page = page_no
        if buffer_bbox is None:
            buffer_bbox = _bbox_to_dict(prov.bbox)
        buffer_texts.append(text)
        buffer_len += len(text)

    flush()
    return chunks


def _chunk_tables(doc: DoclingDocument) -> list[dict]:
    """Convert each Docling table to a Markdown string and return as 'table' chunks."""
    chunks = []
    for table in doc.tables:
        md = table.export_to_markdown(doc)
        if not (md or "").strip():
            continue
        prov = table.prov[0] if table.prov else None
        chunks.append({
            "page_number": prov.page_no if prov else 1,
            "text": md.strip(),
            "bbox": _bbox_to_dict(prov.bbox) if prov else None,
            "chunk_type": "table",
        })
    return chunks


async def _describe_picture(pic, doc: DoclingDocument) -> dict | None:
    """Render a Docling picture item to a base64 PNG and get a vision-LLM description."""
    try:
        pil = pic.get_image(doc)
        if pil is None:
            return None
        b64 = pic._image_to_base64(pil)
        caption = pic.caption_text(doc) if hasattr(pic, "caption_text") else ""
        description = await describe_visual_async(b64, hint=caption or "")
        if not description:
            return None
        prov = pic.prov[0] if pic.prov else None
        return {
            "page_number": prov.page_no if prov else 1,
            "text": description,
            "bbox": _bbox_to_dict(prov.bbox) if prov else None,
            "chunk_type": "vision",
        }
    except Exception:
        return None  # never let a single broken image fail the whole document


def _parse_sync(local_path: str) -> tuple[DoclingDocument, list[dict], int | None]:
    """Run Docling end-to-end; auto-retry with OCR if no text is found on first pass."""
    result = _converter().convert(local_path)
    doc = result.document
    text_chunks = _chunk_document(doc)

    if not text_chunks:
        result = _converter_ocr().convert(local_path)
        doc = result.document
        text_chunks = _chunk_document(doc)

    table_chunks = _chunk_tables(doc)
    page_count = len(doc.pages) if doc.pages else None
    return doc, text_chunks + table_chunks, page_count


async def _mark_status(document_id: uuid.UUID, status: DocumentStatus, error_message: str | None = None) -> Document | None:
    async with async_session_maker() as db:
        document = await db.get(Document, document_id)
        if document is None:
            return None
        document.status = status
        if error_message is not None:
            document.error_message = error_message[:1000]
        await db.commit()
        await db.refresh(document)
        return document


async def process_document_async(document_id_str: str) -> None:
    document_id = uuid.UUID(document_id_str)

    document = await _mark_status(document_id, DocumentStatus.processing)
    if document is None:
        return

    tmp_path = None
    try:
        fd, tmp_path = tempfile.mkstemp(suffix=".pdf")
        os.close(fd)

        def _download_and_parse() -> tuple[DoclingDocument, list[dict], int | None]:
            with open(tmp_path, "wb") as fh:
                storage.download_fileobj(document.storage_key, fh)
            return _parse_sync(tmp_path)

        doc, sync_chunks, page_count = await asyncio.to_thread(_download_and_parse)

        # Vision chunks require async LLM calls — gather them concurrently.
        vision_chunks = [
            c for c in await asyncio.gather(*[_describe_picture(p, doc) for p in doc.pictures])
            if c is not None
        ]
        all_chunk_dicts = sync_chunks + vision_chunks

        if not all_chunk_dicts:
            raise ValueError("No extractable content found (text, tables, or figures).")

        async with async_session_maker() as db:
            document = await db.get(Document, document_id)
            chunk_rows = [
                DocumentChunk(
                    document_id=document.id,
                    page_number=c["page_number"],
                    chunk_index=i,
                    text=c["text"],
                    bbox=c["bbox"],
                    chunk_type=c.get("chunk_type", "text"),
                )
                for i, c in enumerate(all_chunk_dicts)
            ]
            db.add_all(chunk_rows)
            await db.flush()

            vectors = await asyncio.to_thread(embed_texts, [row.text for row in chunk_rows])
            await asyncio.to_thread(
                vector_store.upsert_chunks,
                document.user_id, document.id,
                [row.id for row in chunk_rows],
                vectors,
            )

            document.page_count = page_count
            document.status = DocumentStatus.ready
            document.error_message = None
            await db.commit()

    except Exception as exc:
        await _mark_status(document_id, DocumentStatus.failed, error_message=str(exc))
    finally:
        if tmp_path and os.path.exists(tmp_path):
            os.remove(tmp_path)
